import csv
from datetime import datetime
from collections import defaultdict
from pathlib import Path
import math

# Locate the CSV file that main.py is generating
BASE_DIR = Path(__file__).resolve().parent
CSV_PATH = BASE_DIR / "data" / "temp_humid_training_data.csv"

def get_hourly_sequence():
    """
    Reads the local CSV file generated by the ESP32, averages the 5-minute intervals
    into hourly buckets, and returns the exact 24x4 matrix for the GRU model.
    """
    if not CSV_PATH.exists():
        print(f"⚠️ CSV file not found at {CSV_PATH}. Make sure ESP32 is sending data.")
        return _get_fallback_sequence()

    hourly_buckets = defaultdict(list)

    try:
        with open(CSV_PATH, mode='r', encoding='utf-8') as f:
            reader = csv.reader(f)
            rows = list(reader)

        # We only need the last 24 hours of data. 
        # (12 readings/hr * 24 hrs = 288). We grab the last 400 rows to be safe.
        recent_rows = rows[-400:]

        for row in recent_rows:
            # Skip empty or malformed rows, and skip the header if there is one
            if len(row) < 4 or row[0] == "timestamp": 
                continue 

            # Parse the CSV format written by main.py: 
            # 2026/05/16 06:20:00, 26.5, 60.0, 27.2
            time_str, temp, humid, out_temp = row
            
            try:
                dt = datetime.strptime(time_str, "%Y/%m/%d %H:%M:%S")
                bucket_key = dt.strftime('%Y-%m-%d %H:00')
                hour_of_day = float(dt.hour)

                t1 = float(temp)
                h1 = float(humid)
                t2 = float(out_temp)

                # Drop the data into the correct Hour Bucket
                hourly_buckets[bucket_key].append((hour_of_day, t1, h1, t2))
            except ValueError:
                continue

        # Calculate the average for each hourly batch
        sequence = []
        for bucket_key in sorted(hourly_buckets.keys()):
            batch = hourly_buckets[bucket_key]
            
            avg_hour = batch[0][0] 
            avg_t1 = sum(item[1] for item in batch) / len(batch) # Indoor Temp
            avg_h1 = sum(item[2] for item in batch) / len(batch) # Humidity
            avg_t2 = sum(item[3] for item in batch) / len(batch) # Outdoor Temp
            
            # THE FIX: Match dataset.py format exactly! [Indoor, Outdoor, Humidity, Time_Sin]
            time_sin = round(math.sin(avg_hour * (2 * math.pi / 24)), 4)
            sequence.append([avg_t1, avg_t2, avg_h1, time_sin])

        # Ensure we send exactly the last 24 hours to the GRU
        if len(sequence) < 24:
            while len(sequence) < 24:
                sequence.insert(0, sequence[0] if sequence else [25.0, 27.0, 60.0, 0.0])

        return sequence[-24:]

    except Exception as e:
        print(f"⚠️ Error reading local CSV: {e}")
        return _get_fallback_sequence()

def _get_fallback_sequence():
    """Returns a dummy 24x4 sequence matching the [Indoor, Outdoor, Hum, Time] shape."""
    import math
    print("Injecting fallback sequence into GRU...")
    return [
        [25.0 + (h % 5)*0.2, 27.0 + (h % 5)*0.1, 60.0 + (h % 3), round(math.sin(h * (2 * math.pi / 24)), 4)] 
        for h in range(24)
    ]